### ISSUE TITLE
Erreur dans la génération du séquenceur

### ISSUE THREAD

**Issue by jmchiappa** [Okimi-/Blockly4Thymio-Compilateur#2]
J'ai essayé de compiler un graphe basique dont le fichier xml et le fichier AESL issu  de la compilation sont en attaché.

[programmeBuggé.aesl.txt](https://github.com/Okimi-/Blockly4Thymio-Compilateur/files/818781/programmeBugge.aesl.txt)
[programme (1).b4t.txt](https://github.com/Okimi-/Blockly4Thymio-Compilateur/files/818780/programme.1.b4t.txt)

J'observe que le séquenceur a plusieurs fois l'état 7:
```
 # (UID 6) Instruction Blockly : 0_1b_Mouvement_Recule_SELVitesse_SAIDistance
  if __sequenceur[0]==6 then
    motor.left.target=-250 motor.right.target=-250
    __sequenceur[0]=7
  end
  if __sequenceur[0]==7 then
    if __odo.x&lt;-250 then
      callsub __ArreteLesMoteurs
      __sequenceur[0]=8
    end
  end
```
et
```
# (UID 7) Instruction Blockly : 0_1b_Lumières_AllumeToutesLesLEDs_SELCouleur
  if __sequenceur[0]==7 then
    __led.rouge=31 __led.vert=0 __led.bleu=0 callsub __AllumeLesLEDs
    __sequenceur[0]=8
  end
```
ce qui rend Thymio incohérent avec le programme attendu.
Merci d'avance de votre aide.
Jean-Marc Chiappa

**Comment by Okimi-** [comment]
Bonjour et merci pour ce retour, vous avez levé deux problèmes :

- le premier : vous utilisez une ancienne version du compilateur
Blockly4Thymio (la version 0.8). La nouvelle version 1.1 (disponible sur le
site www.blockly4thymio.net) corrige ce problème d'incohérence dans le
programme attendu... Je vous conseil de désinstaller votre version de
BLockly4Thymio et d'installer la dernière version...

- le second : l'instruction (le bloc) "il n'y a pas d'obstacle derrière"
comporte une erreur de traduction, ce bloc sera corrigé à la prochaine mise
à jour de Blockly4Thymio....

Cordialement

*Okimi - Créateur de Blockly4Thymio*
*Blockly4Thymio, environnement de programmation pour le robot Thymio II.*







Le 4 mars 2017 à 18:05, Jean-Marc CHIAPPA <notifications@github.com> a
écrit :

**Comment by jmchiappa** [comment]
Bonjour, merci pour votre retour.

Je viens de voir la branche 1.1... Merci pour l'information. Je vais la compiler pour LINUX (sous mono-dev ça marche bien).
Dites-moi aussi si vous avez besoin de forces vives pour maintenir et développer cet outil.

Cordialement,
Jean-Marc Chiappa

**Comment by Okimi-** [comment]
Bonsoir,

Le projet est prévue pour mono-dev et la compilation devrait bien
fonctionner... Par contre, je rencontre toujours des problèmes pour le
transfert du fichier .aesl vers thymio. J'utilise un des programme livré
avec Scratch4Thymio, nommé asebahttp mais la version linux semble ne pas
fonctionner...

Merci pour votre proposition, c'est une grande joie que de compter un
collaborateur de plus sur ce projet... Avez-vous des notions de compilation
c++ sous linux ? Ce serait l'occasion de vérifier le programme asebahttp
qui pose problème...

Emmanuel Fort

*Okimi - Créateur de Blockly4Thymio*
*Blockly4Thymio, environnement de programmation pour le robot Thymio II.*







Le 6 mars 2017 à 09:54, Jean-Marc CHIAPPA <notifications@github.com> a
écrit :

**Comment by jmchiappa** [comment]
entendu, je regarde ça... vous n'utilisez pas asebahttp fourni avec aseba Studio ? Il me semblait que le chemin dans le source code du compilateur pointait sur aseba studio.
Je regarde si il y a une différence entre les deux aussi.
Jean-Marc

**Comment by jmchiappa** [comment]
Je viens d'installer la version 1.1 et j'ai recompilé mon fichier b4t. il semble que la séquence suivante est à ajouter dans le fichier Compilateur.cs ligne 642:

```
		case "0_7_Valeur_Booléen_Capteur_ArrièreAucun" :
			expression = new __Valeur(	_UIDPourLeBloc, _XMLDuBloc, _blocPrécédent, _groupeDeBlocs,
										__CAPTEURS.code( (int)__CAPTEURS.NOM.ARRIÈRE_AUCUN, (int)__CAPTEURS.PARAMÈTRE.DISTANCE_PRÈS ) );
			break;

```
Qu'en pensez-vous ?

**Comment by jmchiappa** [comment]
Je viens de tester asebahttp fourni avec aseba Studio. La compilation s'est bien passé sous mono-dev. L'execution en mode DEBUG sous linux s'est bien passé. La programmation de Thymio (ser:Thymio-II) s'est bien passée
Je n'ai pas eu d'erreur de programmation.
Auriez-vous le log d'exécution avec l'erreur ?
Version ASEBA STUDIO:
Version information

> Aseba ver. 1.5.5
> (build ver. 1.5.5/protocol ver. 5)
> Dashel ver. 1.1.0
> (supported stream types: can, file, ser, stdin, stdout, tcp, tcpin, udp)

Bonne soirée.

**Comment by Okimi-** [comment]
Bonjour !

J'ai eu aussi cette erreur hier, dans la foulé, j'ai crée une branche pour
la future version 1.2, dans cette branche du projet, cette erreur est
corrigée...



Le 7 mars 2017 à 23:26, Jean-Marc CHIAPPA <notifications@github.com> a
écrit :

**Comment by Okimi-** [comment]
Je viens de trouver la solution pour le problème d'asebahttp, comme pour la
version windows, j'utilise la version d'asebahttp fournit par le créateur
de thymio pour scratch... Cette version d'asebahttp est légèrement
différente de la version officielle fournt avec asebastudio...

Je vous la transmet en pièce jointe... Pour mes tests j'ai mis ce fichier
dans usr/share/blockly4thymio




Le 7 mars 2017 à 23:09, Jean-Marc CHIAPPA <notifications@github.com> a
écrit :

**Comment by jmchiappa** [comment]
bonjour,

Je vais essayer avec cette version d'asebahttp.
Je comparerai aussi avec celle d'abesa studio.

Bonne journée

**Comment by jmchiappa** [comment]
Je ne trouve pas cette pièce jointe.

**Comment by Okimi-** [comment]
Bonjour,

Le plus simple serait peut-être de communiquer directement par email, qu'en
pensez-vous ?
Voici mon adresse : contact@okimi.net




2017-03-08 13:47 GMT+01:00 Jean-Marc CHIAPPA <notifications@github.com>:
